
name: Build and publish

on:
  push:
    tags:
       - 'v*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web
        uses: actions/checkout@v3
        with:
          repository: javfg/web
          path: web
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout SDK
        uses: actions/checkout@v3
        with:
          repository: javfg/owncloud-sdk
          path: owncloud-sdk
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Build SDK
        run: |
          cd owncloud-sdk
          yarn install
          yarn build:system
      - name: Build Web
        run: |
          export TITLE=CERNBox
          export SOURCE_MAP=true
          export REQUIRE_TIMEOUT=20
          export CDN=true

          cd web
          yarn link ../owncloud-sdk
          make dist
      - name: Create release
        run: |
          mkdir -p release
          tar -C web/dist -czf release/web.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: release/web.tar.gz
      - name: Create tag in web repo
        run: |
          cd web
          git tag ${GITHUB_REF/refs\/tags\//}
          git push --tags
